### ISSUE TITLE
Fix Install Runtime Path

### ISSUE THREAD

**Issue by nibanks** [nibanks/msh3#12]
CMake install currently outputs:
```
-- Set runtime path of "/usr/local/lib/libmsh3.so" to ""
```
We need to figure out how to properly configure that.

**Comment by thhous-msft** [comment]
That is actually the default runtime path. RPATHs in linux are really weird. Its kind of 50/50 on if you should leave the defaults or configure them. Its probably best to just leave it default.

**Comment by nibanks** [comment]
Ok. I will close this for now.
