### ISSUE TITLE
Add Version to Binaries

### ISSUE THREAD

**Issue by nibanks** [nibanks/msh3#23]

**Comment by bagder** [comment]
While the comment in curl mention adding to the header file, it works better if provided by a function so that we can ask for the version number of the library at run-time. Presumably in a future we could upgrade this library without recompiling users (when the ABI remains compatible).

Maybe just something simple like:
~~~c
const char *MsH3Version(void);

**Comment by nibanks** [comment]
Yeah, I agree. Though m preference lends towards returning the raw numbers instead of a string. But we definitely need to be explicit about the versioning.

**Comment by bagder** [comment]
I understand. For example both brotil and zstd return major + minor + patch instead as a number. Shown below for inspiration is how we extract the version number from those:

## brotli
~~~c
static void brotli_version(char *buf, size_t bufsz)
{
  uint32_t brotli_version = BrotliDecoderVersion();
  unsigned int major = brotli_version >> 24;
  unsigned int minor = (brotli_version & 0x00FFFFFF) >> 12;
  unsigned int patch = brotli_version & 0x00000FFF;
  (void)msnprintf(buf, bufsz, "%u.%u.%u", major, minor, patch);
}
~~~

## zstd:
~~~c
static void zstd_version(char *buf, size_t bufsz)
{
  unsigned long zstd_version = (unsigned long)ZSTD_versionNumber();
  unsigned int major = (unsigned int)(zstd_version / (100 * 100));
  unsigned int minor = (unsigned int)((zstd_version -
                                       (major * 100 * 100)) / 100);
  unsigned int patch = (unsigned int)(zstd_version -
                                      (major * 100 * 100) - (minor * 100));
  (void)msnprintf(buf, bufsz, "%u.%u.%u", major, minor, patch);
}
~~~

**Comment by nibanks** [comment]
I'm playing around with this right now. Currently I have:
```c
void
MSH3_CALL
MsH3Version(
    uint32_t Version[4]
    );
```
